%#-*- coding:utf-8 -*-
\chapter{内建异常}
在Python中，所有的异常类型都派生于BaseException类。In a try statement with an except clause that mentions a particular
class, that clause also handles any exception classes derived from that class (but not exception classes from which it
is derived). Two exception classes that are not never equivalent, even if they have the same name.
\par
The built-in exceptions listed below can be generated by the interpreter or built-in functions. Except where mentioned,
they have an \textquotedblleft{associated value}\textquotedblright{} indicating the detailed cause of the error. This
may be a string or a tuple of several items of information (e.g., an error code and a string explaining the code). The
associated value is usually passed as arguments to the exception class’s constructor.
\par
User code can raise built-in exceptions. This can be used to test an exception handler or to report an error condition
\textquotedblleft{just like}\textquotedblright{} the situation in which the interpreter raises the same exception; but
beware that there is nothing to prevent user code from raising an inappropriate error.
\par
The built-in exception classes can be subclassed to define new exceptions; programmers are encouraged to derive new
exceptions from the Exception class or one of its subclasses, and not from BaseException. More information on defining
exceptions is available in the Python Tutorial under User-defined Exceptions.
\par

\subsection{基类}
下面的几个异常类型几乎作为其它异常类型的基类。

\noindent{\color{red}{exception BaseException:}}
\par{所有异常类的积累。}\\

\noindent{\color{red}{excetion Exception:}}
\par{未知}\\

\noindent{\color{red}{exception ArithmeticError:}}
\par{未知}\\

\noindent{\color{red}{exception BufferError:}}
\par{未知}\\

\noindent{\color{red}{exception LookupError:}}
\par{未知}\\






\subsection{具体类}
\noindent{\color{red}{exception AssertionError:}}
\par{断言失败抛出的异常类型。}\\

\noindent{\color{red}{exception AttributeError:}}
\par{Raised when an attribute reference (see Attribute references) or assignment fails. (When an object does not support
 attribute references or attribute assignments at all, TypeError is raised.)}\\

\noindent{\color{red}{exception EOFError:}}
\par{Raised when the input() function hits an end-of-file condition (EOF) without reading any data. (N.B.: the
  io.IOBase.read() and io.IOBase.readline() methods return an empty string when they hit EOF.)}\\

\noindent{\color{red}{exception FloatingPointError:}}
\par{Raised when a floating point operation fails. This exception is always defined, but can only be raised when Python
  is configured with the --with-fpectl option, or the WANT\_SIGFPE\_HANDLER symbol is defined in the pyconfig.h file.}\\

\noindent{\color{red}{exception GeneratorExit:}}
\par{Raised when a generator or coroutine is closed; see generator.close() and coroutine.close(). It directly inherits
  from BaseException instead of Exception since it is technically not an error.}\\

\noindent{\color{red}{exception ImportError:}}
\par{Raised when the import statement has troubles trying to load a module. Also raised when the “from list” in from
 \dots import has a name that cannot be found.}\\

\noindent{\color{red}{exception ModuleNotFoundError:}}
\par{A subclass of ImportError which is raised by import when a module could not be located. It is also raised when None
is found in sys.modules.}\\








%%% Local Variables:
%%% mode: latex
%%% TeX-master: t
%%% End:
